### ISSUE TITLE
Search does not include arrays

### ISSUE THREAD

**Issue by axit-joost** [Wizcorp/express-rested#47]
If you have a `Resource` that has properties in the form of an `Array`, you cannot perform a `collection.findOne()` or `collection.findAll()` on it. It will simply return an empty `Array` as the result.

Say you have a `Resource` that has a `tags` property, which is an `Array` of said tags, you might want to use `findOne()` or `findAll()` to find all the resources that match a given tag.

```yaml
1:
  id: 1
  name: Heineken
  tags:
  - hoofdpijn
  - bagger
2:
  id: 2
  name: Grolsch
  tags:
  - bagger
3:
  id: 3
  name: Jupiler
  tags:
  - lekker
  - belgisch
```
```js
beers.addIndex('tags');
beers.findOne('tags', 'belgisch'); // returns []
beers.findOne('tags', 'hoofdpijn'); // returns []
beers.findAll('tags', 'bagger'); // returns []
```
